env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: 
  quotes: 
    - error
    - double
  react/jsx-filename-extension: off
  import/prefer-default-import: off
  react/jsx-props-no-spreading: off
  react/prop-types: 1
  import/extensions: off
  max-len: 
    - warn
    - code: 140
  jsx-a11y/no-noninteractive-tabindex:
    - warTabinden
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
